[package]
name = "lang_classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.13.2", features = ["dataset", "wgpu"] }
csv = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
